Week5CodeChallenge/Models/SimoneEntitiesValidation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//add a using statement for data annotations
using System.ComponentModel.DataAnnotations;

namespace Week5CodeChallenge.Models
{

    //create a partial class for SimoneEntities
    //so we can connect the validation properties with
    //MetaData
    [MetadataType(typeof(Week5CodeChallengeValidation))]
    public partial class Week5CodeChallenge
    {
    
    }



    


    public class Week5CodeChallengeValidation
    {
        
       [Required, 
        Display(Name="First Name")
        ,MaxLength(50)]
        public string FirstName { get; set; }
        [Required,
        Display(Name="Last Name")
        ,MaxLength(50)]
        public string LastName { get; set; }
        [Required
        ,Display(Name="Email")
        ,MaxLength(50)]
        public string Email { get; set; }
        [Required
        ,Display(Name="Phone Number")
        ]
        public int PhoneNumber { get; set; }
        [Required
        ,Display(Name="Company Name")
        ,MaxLength(50)]
        public string CompanyName { get; set; }
        [Required
        ,Display(Name="Project Description")
        ,MaxLength(50)]
        public string ProjectDescription { get; set; }
        [Required
        ,Display(Name="Comment")
        ,MaxLength(50)]
        public string Comment { get; set; }
    }
}

    

Week5CodeChallenge/Models/Week5CodeChallenge.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week5CodeChallenge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimoneEntities : DbContext
    {
        public SimoneEntities()
            : base("name=SimoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Week5CodeChallenge> Week5CodeChallenge { get; set; }
    }
}

Week5CodeChallenge/Models/Week5CodeChallenge.Designer.cs
// Default code generation is disabled for model 'C:\Users\Technologist\Documents\GitHub\ContactFormConsole\Week5CodeChallenge\Models\Week5CodeChallenge.edmx'. 
// To enable default code generation, change the value of the 'Code Generation Strategy' designer
// property to an alternate value. This property is available in the Properties Window when the model is
// open in the designer.

Week5CodeChallenge/Models/Week5CodeChallenge.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week5CodeChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week5CodeChallenge
    {
        public int ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string ProjectDescription { get; set; }
        public string Comment { get; set; }
    }
}

Week5CodeChallenge/Models/Week5CodeChallenge1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Week5CodeChallenge/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Week5CodeChallenge/Controllers/CareersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class CareersController : Controller
    {
        //
        // GET: /Career/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Week5CodeChallenge/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        [HttpGet]
        public ActionResult Index()
        {
      
            Models.Week5CodeChallenge cf = new Models.Week5CodeChallenge();
            return View(cf);
        }

   
       
    [HttpPost]
        public ActionResult Index(Models.Week5CodeChallenge cf)
        {
            //establish a connection to the database
            var db = new Models.SimoneEntities();
            //add contact form to database
            db.Week5CodeChallenge.Add(cf);
            db.SaveChanges();
            return RedirectToAction("ThankYou");
        }
        //Get Contact thank you
        public ActionResult ThankYou() {

            return View();
        
        }
    }
}

Week5CodeChallenge/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }
        // Get:/Home/About

        public ActionResult Who()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }
    
        // Get:/Home/Work
        public ActionResult What()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }
        // Get:/Home/Careers
        public ActionResult Where()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }
        
        //Get:/Home/Contact
        public ActionResult Why()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }
    }
}

Week5CodeChallenge/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class WorkController : Controller
    {
        //
        // GET: /Work/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Week5CodeChallenge/Views/Contact/Index.cshtml
@model Week5CodeChallenge.Models.Week5CodeChallenge

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>




@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Week5CodeChallenge</legend>

               <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PhoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhoneNumber)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CompanyName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CompanyName)
            @Html.ValidationMessageFor(model => model.CompanyName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectDescription)
            @Html.ValidationMessageFor(model => model.ProjectDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comment)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Comment)
            @Html.ValidationMessageFor(model => model.Comment)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Week5CodeChallenge/Views/Contact/ThankYou.cshtml
@{
    ViewBag.Title = "ThankYou";
}

<h2>ThankYou, you're the best.</h2>

Week5CodeChallenge/Views/Home/About.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>About</h2>
<nav>
<div class="tabs-block" id="aboutContainer">
    <li>
        Who?
    </li>
    <li>
        What?
    </li>
    <li>
        Where?
    </li>
    <li>
        Why?
    </li>
    <li>
        How?
    </li>
</div>
</nav>
<div>
    <div id ="tabContent"
    @Html.Partial("who")
</div>

    <div class="tab-content">
                    <div id="who" class="tab-data">
                        <h2>Who?</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet congue. Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, lobortis consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et massa eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac diam sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel tempus neque pharetra.</p>
                    </div>
                    <div id="what" class="tab-data hide">
                        <h2>What?</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet congue. Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, lobortis consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et massa eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac diam sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel tempus neque pharetra.</p>
                    </div>
                    <div id="why" class="tab-data hide">
                        <h2>Why?</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet congue. Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, lobortis consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et massa eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac diam sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel tempus neque pharetra.</p>
                    </div>
                    <div id="how" class="tab-data hide">
                        <h2>How?</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet congue. Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, lobortis consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et massa eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac diam sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel tempus neque pharetra.</p>
                    </div>
					<div id="where" class="tab-data hide">
						<h2>Where?</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet congue. Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, lobortis consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et massa eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac diam sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel tempus neque pharetra.</p>
					</div>
				</div>

Week5CodeChallenge/Views/Home/Careers.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Careers</h2>

<div class="container">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet congue. Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, lobortis consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et massa eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac diam sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel tempus neque pharetra.
    </p>
</div>

Week5CodeChallenge/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

   @{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="container">
    <div id="div1">
        <img src="http://tinyurl.com/lf-suhbg" />
    </div>
    <div id="div2">
        <h3>Title</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel 
            leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et 
            malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet congue.
             Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, lobortis 
            consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et massa 
            eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac diam 
            sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel tempus
             neque pharetra.</p>
    </div>
    <div id="div3">
        <h3>Title</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel
             leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et
             malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet 
            congue. Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, 
            lobortis consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et 
            massa eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac 
            diam sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel 
            tempus neque pharetra.</p>
    </div>
    <div id="div4">
        <h3>Title</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas felis eget eros pretium, et bibendum leo congue. Integer consectetur sem vel
             leo aliquet, quis porta ligula tincidunt. Morbi id lectus sed dui posuere molestie. Pellentesque habitant morbi tristique senectus et netus et 
            malesuada fames ac turpis egestas. Vestibulum consequat hendrerit turpis, sit amet placerat urna viverra at. Integer interdum nec urna sit amet congue.
             Sed velit lectus, pretium sed bibendum commodo, dictum vel sapien. Mauris ut quam metus. Curabitur justo felis, lacinia aliquet lectus a, lobortis 
            consequat neque. Morbi lacinia, sem sed fringilla porttitor, tortor tellus condimentum sem, et consectetur dui dolor consequat dolor. Nunc et massa 
            eros. Donec facilisis ut velit vitae suscipit. Pellentesque neque justo, ultrices vel consectetur nec, accumsan a elit. Nam venenatis elit ac diam 
            sollicitudin euismod. Curabitur quis lacus eleifend massa porta sagittis sit amet placerat purus. Nullam condimentum ante et ipsum aliquet, vel tempus
             neque pharetra.</p>
    </div>
</div>

Week5CodeChallenge/Views/Home/Work.cshtml
@{
    ViewBag.Title = "Work";
}

<h2>Work</h2>

Week5CodeChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
      <header>
         <img class src="C:\Users\Technologist\Documents\GitHub\ContactFormConsole\Week5CodeChallenge\Content\51700.gif"</a>
        <nav id="navigation">
            <a href="@Url.Action("Index","Home")" class="button">Home Page</a>
            <a href="@Url.Action("Index","About")" class="button">About</a>
            <a href="@Url.Action("Index", "Work")" class="button">Work</a>
            <a href="@Url.Action("Index", "Careers")" class="button">Careers</a>
            <a href="@Url.Action("Index", "Contact")" class="button">Contact</a>
        </nav>d4
    </header>
    <br style="clear:both;"/>
    
    @RenderBody()
    
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/Main.js"></script>
    @RenderSection("scripts", required: false)
    <div id="left" class="footer">
        <footer style="font-size: 20px">
            Copyright 2014 Fake Studio
        </footer>
    </div>
    <div id="right" class="footer">
        <footer>
            <a href="@Url.Action("Index","Home")" class="button2">Home Page</a>
            <a href="@Url.Action("Index","About")" class="button2">About</a>
            <a href="@Url.Action("Index", "Work")" class="button2">Work</a>
            <a href="@Url.Action("Index", "Careers")" class="button2">Careers</a>
            <a href="@Url.Action("Index", "Contact")" class="button2">Contact</a>
        </footer>
    </div>
</body>
</html>
    
    
    
    
    
    
    